# Generated by Django 2.1.3 on 2018-11-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='expire_time',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('N', 'Normal'), ('I', 'Important'), ('C', 'Critical')], default='N', max_length=1),
        ),
    ]
