# Generated by Django 2.1.3 on 2018-11-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20181117_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='expire_time',
            new_name='expire_date',
        ),
    ]
