# Generated by Django 2.1.3 on 2018-11-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_todolist_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
